/**
 * Render-performance harness for large builds.
 *
 * Measurement method: requestAnimationFrame delta sampling.
 * A loop of ≥ 60 consecutive rAF callbacks records the elapsed time between
 * each pair of adjacent frames. The p95 of those deltas must stay at or below
 * ~17 ms (≈ 60 fps) to pass.
 *
 * The test deterministically regenerates a 2 000-brick stress build in-process
 * using the same algorithm as scripts/gen-stress-build.ts so CI never needs
 * network or file-system access. The checked-in fixtures/stress-build-2k.json
 * is the canonical artefact generated by `npm run gen:stress-build`.
 *
 * When a 3-D canvas with camera orbit controls is added, the pointer-drag
 * simulation below will naturally exercise the GPU-bound render path.
 */

import { test, expect } from '@playwright/test'

import {
  BUDGET_DOC_URL,
  MIN_SAMPLE_FRAMES as SAMPLE_FRAMES,
  P95_FRAME_BUDGET_MS as P95_BUDGET_MS,
} from './budgets'

// Mirror of constants from src/domain/grid — inlined so this file needs no
// node built-ins and remains within tsconfig.app.json's browser type context.
const BASEPLATE_SIZE_STUDS = 32
const BRICK_HEIGHT_PLATES = 3
const COLORS = [
  'red',
  'blue',
  'yellow',
  'green',
  'white',
  'black',
  'orange',
  'gray',
] as const

interface SerializedBrick {
  partId: string
  color: string
  x: number
  y: number
  z: number
  rot: 0 | 1 | 2 | 3
}

interface PlacedBrick extends SerializedBrick {
  id: string
}

/**
 * Deterministic stress-build generator — same algorithm as
 * scripts/gen-stress-build.ts. Produces N 1×1 bricks placed layer by layer
 * across the 32×32 stud grid.
 */
function generateBricks(count: number): PlacedBrick[] {
  const bricks: PlacedBrick[] = []
  const cellsPerLayer = BASEPLATE_SIZE_STUDS * BASEPLATE_SIZE_STUDS

  let remaining = count
  let layer = 0

  while (remaining > 0) {
    const bricksThisLayer = Math.min(remaining, cellsPerLayer)
    for (let i = 0; i < bricksThisLayer; i++) {
      const x = i % BASEPLATE_SIZE_STUDS
      const z = Math.floor(i / BASEPLATE_SIZE_STUDS)
      const colorIndex = (x + z + layer) % COLORS.length
      bricks.push({
        id: `perf-${layer}-${i}`,
        partId: 'brick-1x1',
        color: COLORS[colorIndex],
        x,
        y: layer * BRICK_HEIGHT_PLATES,
        z,
        rot: 0,
      })
    }
    remaining -= bricksThisLayer
    layer++
  }

  return bricks
}

test('p95 frame time ≤ 17ms with 2 000-brick stress build', async ({
  page,
}) => {
  await page.goto('/')

  // Inject stress build into the canonical Zustand store via the dev-mode
  // window handle exposed in src/main.tsx when import.meta.env.DEV is true.
  const bricks = generateBricks(2000)
  await page.evaluate((bricksJson) => {
    const store = (
      window as Window & {
        __blockyStore?: {
          setState: (state: { bricks: Record<string, unknown> }) => void
        }
      }
    ).__blockyStore
    store?.setState({
      bricks: Object.fromEntries(bricksJson.map((brick) => [brick.id, brick])),
    })
  }, bricks)

  // Wait for the DOM to reflect the injected build.
  await expect(page.locator('.brick-count')).toBeVisible({ timeout: 15000 })

  // Simulate orbit/pan-style pointer drag across the viewport so that when a
  // 3-D canvas is present the GPU render path is exercised on every frame.
  const box = await page.locator('main').boundingBox()
  if (box) {
    const cx = box.x + box.width / 2
    const cy = box.y + box.height / 2
    await page.mouse.move(cx - 100, cy)
    await page.mouse.down()
    for (let dx = -100; dx <= 100; dx += 10) {
      await page.mouse.move(cx + dx, cy)
    }
    await page.mouse.up()
  }

  // Sample ≥ SAMPLE_FRAMES consecutive rAF deltas.
  // Each entry is the elapsed ms between adjacent animation frames.
  const frameTimes: number[] = await page.evaluate(
    ({ frames }) =>
      new Promise<number[]>((resolve) => {
        // requestAnimationFrame delta sampling:
        // record the timestamp of each callback and compute the delta to the
        // previous one; accumulate until we have `frames` deltas.
        const deltas: number[] = []
        let prev = -1

        function tick(ts: number) {
          if (prev >= 0) deltas.push(ts - prev)
          prev = ts
          if (deltas.length < frames) {
            requestAnimationFrame(tick)
          } else {
            resolve(deltas)
          }
        }

        requestAnimationFrame(tick)
      }),
    { frames: SAMPLE_FRAMES },
  )

  expect(frameTimes.length).toBeGreaterThanOrEqual(SAMPLE_FRAMES)

  const sorted = [...frameTimes].sort((a, b) => a - b)
  const p95Index = Math.floor(sorted.length * 0.95)
  const p95 = sorted[p95Index]!

  // Assert the 60 fps budget: p95 frame time must be ≤ 17ms.
  expect(
    p95,
    `p95 frame time ${p95.toFixed(1)}ms exceeds the ${P95_BUDGET_MS}ms render budget. See ${BUDGET_DOC_URL} for details.`,
  ).toBeLessThanOrEqual(P95_BUDGET_MS)
})
