import { execFileSync } from 'node:child_process'
import {
  mkdtempSync,
  mkdirSync,
  writeFileSync,
  readFileSync,
  rmSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'

const ROOT = process.cwd()

// Husky v9 invokes each `.husky/<hook>` entrypoint via `sh -e "$s" "$@"` and
// exits with its status — see node_modules/husky/husky. Anything appended
// after that call in the generated `.husky/_/<hook>` shims is unreachable,
// and those shims are regenerated (wiping any appended content) every time
// `npm run prepare` (husky install) runs. The beads integration therefore
// must live inside the versioned `.husky/<hook>` entrypoints, which this
// test proves by actually executing them with stubbed dependencies.
const HOOKS_DIR = join(ROOT, '.husky')

let stubDir: string
let logPath: string

function makeStub(command: string) {
  writeFileSync(
    join(stubDir, command),
    `#!/usr/bin/env sh\necho "${command} $*" >> "${logPath}"\nexit 0\n`,
    { mode: 0o755 },
  )
}

function runHook(hookName: string, extraArgs: string[] = []) {
  const hookPath = join(HOOKS_DIR, hookName)
  return execFileSync('sh', ['-e', hookPath, ...extraArgs], {
    env: { ...process.env, PATH: `${stubDir}:${process.env.PATH}` },
    encoding: 'utf-8',
  })
}

function readLog(): string {
  return readFileSync(logPath, 'utf-8')
}

describe('beads git hook integration (installed hooks actually run)', () => {
  afterEach(() => {
    rmSync(stubDir, { recursive: true, force: true })
  })

  function setupStubs() {
    stubDir = mkdtempSync(join(tmpdir(), 'beads-hook-stubs-'))
    logPath = join(stubDir, 'calls.log')
    writeFileSync(logPath, '')
    makeStub('npx')
    makeStub('npm')
    makeStub('bd')
  }

  it('pre-commit runs lint-staged, typecheck, and bd dispatch', () => {
    setupStubs()
    runHook('pre-commit')
    const log = readLog()
    expect(log).toMatch(/npx lint-staged/)
    expect(log).toMatch(/npm run typecheck/)
    expect(log).toMatch(/bd hooks run pre-commit/)
  }, 20000)

  it('pre-push runs the test suite and bd dispatch', () => {
    setupStubs()
    runHook('pre-push')
    const log = readLog()
    expect(log).toMatch(/npm run test/)
    expect(log).toMatch(/bd hooks run pre-push/)
  }, 20000)

  it('post-checkout dispatches to bd', () => {
    setupStubs()
    runHook('post-checkout', ['prev-head', 'new-head', '1'])
    expect(readLog()).toMatch(/bd hooks run post-checkout prev-head new-head 1/)
  }, 20000)

  it('post-merge dispatches to bd', () => {
    setupStubs()
    runHook('post-merge', ['1'])
    expect(readLog()).toMatch(/bd hooks run post-merge 1/)
  }, 20000)

  it('prepare-commit-msg dispatches to bd with the passed-through args', () => {
    setupStubs()
    runHook('prepare-commit-msg', ['.git/COMMIT_EDITMSG', 'message'])
    expect(readLog()).toMatch(
      /bd hooks run prepare-commit-msg \.git\/COMMIT_EDITMSG message/,
    )
  }, 20000)

  it('skips bd dispatch cleanly when bd is not on PATH', () => {
    stubDir = mkdtempSync(join(tmpdir(), 'beads-hook-stubs-'))
    logPath = join(stubDir, 'calls.log')
    writeFileSync(logPath, '')
    makeStub('npx')
    makeStub('npm')
    // no `bd` stub — command -v bd should fail and the hook should still succeed
    expect(() => runHook('pre-commit')).not.toThrow()
    const log = readLog()
    expect(log).toMatch(/npx lint-staged/)
    expect(log).toMatch(/npm run typecheck/)
    expect(log).not.toMatch(/bd hooks run/)
  }, 20000)

  it('every generated .husky/_/<hook> shim only sources h (no unreachable trailing code)', () => {
    mkdirSync(join(HOOKS_DIR, '_'), { recursive: true })
    for (const hook of [
      'pre-commit',
      'pre-push',
      'post-checkout',
      'post-merge',
      'prepare-commit-msg',
    ]) {
      const shim = readFileSync(join(HOOKS_DIR, '_', hook), 'utf-8')
      expect(
        shim,
        `.husky/_/${hook} must not carry beads integration — it is ` +
          'regenerated by "npm run prepare" and control never returns to ' +
          'code appended after sourcing "h"',
      ).not.toMatch(/bd hooks run/)
    }
  })
})
